apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: train
        image: IMAGE
        ports:
        - containerPort: 3000
