apiVersion: apps/v1
kind: Deployment
metadata:
  name: Abstergo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Abstergo-app
  template:
    metadata:
      labels:
        app: Abstergo-app
    spec:
      containers:
      - name: Abstergo-app
        image: navesing2112/Abstergo-app:latest   # Jenkins pipeline will replace this
        ports:
        - containerPort: 3000
