apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abstergo-app
  template:
    metadata:
      labels:
        app: abstergo-app
    spec:
      containers:
        - name: abstergo-app
          image: IMAGE        # <-- placeholder to replace
          ports:
            - containerPort: 3000
